name: MATLAB Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      
      # Sets up MATLAB on the GitHub Actions runner
      - name: Setup MATLAB
        uses: matlab-actions/setup-matlab@v1
  
      - name: Run script
        uses: matlab-actions/run-command@v1
        with:
          command: addpath('01_ideal_pose_maker'),ideal_arm_theta_demo_wave
          #command: ideal_arm_theta_demo_test